# Generated by Django 4.2.1 on 2023-06-07 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agiletrack', '0013_remove_project_cost'),
        ('accounts', '0004_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agiletrack.job'),
        ),
    ]
