# Generated by Django 4.2.1 on 2023-06-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
