PGDMP         4                {        
   agiletrack_hrm9    14.5    14.5 ~    §           0    0    ENCODING    ENCODING        SET client_encoding = 'UTF8';
                      false            ¨           0    0 
   STDSTRINGS 
   STDSTRINGS     (   SET standard_conforming_strings = 'on';
                      false            ©           0    0 
   SEARCHPATH 
   SEARCHPATH     8   SELECT pg_catalog.set_config('search_path', '', false);
                      false            ª           1262    16944 
   agiletrack_hrm9    DATABASE     n   CREATE DATABASE agiletrack_hrm9 WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'English_United States.1252';
    DROP DATABASE agiletrack_hrm9;
                postgres    false            Ü            1259    17008    accounts_employee    TABLE       CREATE TABLE public.accounts_employee (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    image character varying(100),
    job_id bigint
);
 %   DROP TABLE public.accounts_employee;
       public         heap    postgres    false            Ş            1259    17018    accounts_employee_groups    TABLE     ‰   CREATE TABLE public.accounts_employee_groups (
    id bigint NOT NULL,
    employee_id bigint NOT NULL,
    group_id integer NOT NULL
);
 ,   DROP TABLE public.accounts_employee_groups;
       public         heap    postgres    false            İ            1259    17017    accounts_employee_groups_id_seq    SEQUENCE     ï   ALTER TABLE public.accounts_employee_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_employee_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    222            Û            1259    17007    accounts_employee_id_seq    SEQUENCE     á   ALTER TABLE public.accounts_employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    220            à            1259    17024 "   accounts_employee_user_permissions    TABLE     ˜   CREATE TABLE public.accounts_employee_user_permissions (
    id bigint NOT NULL,
    employee_id bigint NOT NULL,
    permission_id integer NOT NULL
);
 6   DROP TABLE public.accounts_employee_user_permissions;
       public         heap    postgres    false            ß            1259    17023 )   accounts_employee_user_permissions_id_seq    SEQUENCE       ALTER TABLE public.accounts_employee_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_employee_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    224            ç            1259    17132    agiletrack_job    TABLE     š   CREATE TABLE public.agiletrack_job (
    id bigint NOT NULL,
    title character varying(50) NOT NULL,
    description character varying(200) NOT NULL
);
 "   DROP TABLE public.agiletrack_job;
       public         heap    postgres    false            æ            1259    17131    agiletrack_job_id_seq    SEQUENCE     Û   ALTER TABLE public.agiletrack_job ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agiletrack_job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    231            å            1259    17126    agiletrack_project    TABLE     q  CREATE TABLE public.agiletrack_project (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(250) NOT NULL,
    start_date date NOT NULL,
    estimated_end_date date NOT NULL,
    end_date date,
    is_completed boolean NOT NULL,
    estimated_duration integer NOT NULL,
    duration integer,
    budget numeric(10,2)
);
 &   DROP TABLE public.agiletrack_project;
       public         heap    postgres    false            ä            1259    17125    agiletrack_project_id_seq    SEQUENCE     ã   ALTER TABLE public.agiletrack_project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agiletrack_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    229            é            1259    17144    agiletrack_sprint    TABLE     \  CREATE TABLE public.agiletrack_sprint (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    goal character varying(250) NOT NULL,
    start_date date,
    estimated_end_date date,
    end_date date,
    estimated_duration integer,
    duration integer,
    status character varying(20) NOT NULL,
    project_id bigint NOT NULL
);
 %   DROP TABLE public.agiletrack_sprint;
       public         heap    postgres    false            è            1259    17143    agiletrack_sprint_id_seq    SEQUENCE     á   ALTER TABLE public.agiletrack_sprint ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agiletrack_sprint_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    233            ë            1259    17150    agiletrack_task    TABLE     Ë  CREATE TABLE public.agiletrack_task (
    id bigint NOT NULL,
    summary character varying(200) NOT NULL,
    description character varying(250) NOT NULL,
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    duration integer,
    status character varying(20) NOT NULL,
    priority character varying(20) NOT NULL,
    cost numeric(10,2) NOT NULL,
    employee_id bigint,
    project_id bigint NOT NULL,
    sprint_id bigint
);
 #   DROP TABLE public.agiletrack_task;
       public         heap    postgres    false            ê            1259    17149    agiletrack_task_id_seq    SEQUENCE     İ   ALTER TABLE public.agiletrack_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agiletrack_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    235            í            1259    17182    agiletrack_team    TABLE        CREATE TABLE public.agiletrack_team (
    id bigint NOT NULL,
    employee_id bigint NOT NULL,
    project_id bigint NOT NULL
);
 #   DROP TABLE public.agiletrack_team;
       public         heap    postgres    false            ì            1259    17181    agiletrack_team_id_seq    SEQUENCE     İ   ALTER TABLE public.agiletrack_team ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agiletrack_team_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    237            Ø            1259    16968 
   auth_group    TABLE     {   CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL,
    short_name text
);
    DROP TABLE public.auth_group;
       public         heap    postgres    false            ×            1259    16967    auth_group_id_seq    SEQUENCE     Ó   ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    216            Ú            1259    16976    auth_group_permissions    TABLE     Š   CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);
 *   DROP TABLE public.auth_group_permissions;
       public         heap    postgres    false            Ù            1259    16975    auth_group_permissions_id_seq    SEQUENCE     ë   ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    218            Ö            1259    16962    auth_permission    TABLE     ¿   CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);
 #   DROP TABLE public.auth_permission;
       public         heap    postgres    false            Õ            1259    16961    auth_permission_id_seq    SEQUENCE     İ   ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    214            î            1259    17217    authtoken_token    TABLE     œ   CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);
 #   DROP TABLE public.authtoken_token;
       public         heap    postgres    false            â            1259    17059    django_admin_log    TABLE     ‡  CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);
 $   DROP TABLE public.django_admin_log;
       public         heap    postgres    false            á            1259    17058    django_admin_log_id_seq    SEQUENCE     ß   ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    226            Ô            1259    16954    django_content_type    TABLE     Ÿ   CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);
 '   DROP TABLE public.django_content_type;
       public         heap    postgres    false            Ó            1259    16953    django_content_type_id_seq    SEQUENCE     å   ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    212            Ò            1259    16946    django_migrations    TABLE     Ä   CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);
 %   DROP TABLE public.django_migrations;
       public         heap    postgres    false            Ñ            1259    16945    django_migrations_id_seq    SEQUENCE     á   ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    210            ã            1259    17115    django_session    TABLE     ª   CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);
 "   DROP TABLE public.django_session;
       public         heap    postgres    false            ’          0    17008    accounts_employee 
   TABLE DATA           ¬   COPY public.accounts_employee (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, image, job_id) FROM stdin;
    public          postgres    false    220   â´       ”          0    17018    accounts_employee_groups 
   TABLE DATA           M   COPY public.accounts_employee_groups (id, employee_id, group_id) FROM stdin;
    public          postgres    false    222   Rº       –          0    17024 "   accounts_employee_user_permissions 
   TABLE DATA           \   COPY public.accounts_employee_user_permissions (id, employee_id, permission_id) FROM stdin;
    public          postgres    false    224   ­º                 0    17132    agiletrack_job 
   TABLE DATA           @   COPY public.agiletrack_job (id, title, description) FROM stdin;
    public          postgres    false    231   Êº       ›          0    17126    agiletrack_project 
   TABLE DATA           ¡   COPY public.agiletrack_project (id, name, description, start_date, estimated_end_date, end_date, is_completed, estimated_duration, duration, budget) FROM stdin;
    public          postgres    false    229   r»       Ÿ          0    17144    agiletrack_sprint 
   TABLE DATA           —   COPY public.agiletrack_sprint (id, name, goal, start_date, estimated_end_date, end_date, estimated_duration, duration, status, project_id) FROM stdin;
    public          postgres    false    233   ½       ¡          0    17150    agiletrack_task 
   TABLE DATA           Ÿ   COPY public.agiletrack_task (id, summary, description, start_date, end_date, duration, status, priority, cost, employee_id, project_id, sprint_id) FROM stdin;
    public          postgres    false    235   p¾       £          0    17182    agiletrack_team 
   TABLE DATA           F   COPY public.agiletrack_team (id, employee_id, project_id) FROM stdin;
    public          postgres    false    237   ûÂ                 0    16968 
   auth_group 
   TABLE DATA           :   COPY public.auth_group (id, name, short_name) FROM stdin;
    public          postgres    false    216   aÃ                 0    16976    auth_group_permissions 
   TABLE DATA           M   COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
    public          postgres    false    218   ”Ã       Œ          0    16962    auth_permission 
   TABLE DATA           N   COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
    public          postgres    false    214   ±Ã       ¤          0    17217    authtoken_token 
   TABLE DATA           @   COPY public.authtoken_token (key, created, user_id) FROM stdin;
    public          postgres    false    238   ËÅ       ˜          0    17059    django_admin_log 
   TABLE DATA           Š   COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
    public          postgres    false    226   ±Ç       Š          0    16954    django_content_type 
   TABLE DATA           C   COPY public.django_content_type (id, app_label, model) FROM stdin;
    public          postgres    false    212   šÉ       ˆ          0    16946    django_migrations 
   TABLE DATA           C   COPY public.django_migrations (id, app, name, applied) FROM stdin;
    public          postgres    false    210   HÊ       ™          0    17115    django_session 
   TABLE DATA           P   COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
    public          postgres    false    227   ÍÍ       «           0    0    accounts_employee_groups_id_seq    SEQUENCE SET     N   SELECT pg_catalog.setval('public.accounts_employee_groups_id_seq', 17, true);
          public          postgres    false    221            ¬           0    0    accounts_employee_id_seq    SEQUENCE SET     G   SELECT pg_catalog.setval('public.accounts_employee_id_seq', 19, true);
          public          postgres    false    219            ­           0    0 )   accounts_employee_user_permissions_id_seq    SEQUENCE SET     X   SELECT pg_catalog.setval('public.accounts_employee_user_permissions_id_seq', 1, false);
          public          postgres    false    223            ®           0    0    agiletrack_job_id_seq    SEQUENCE SET     C   SELECT pg_catalog.setval('public.agiletrack_job_id_seq', 6, true);
          public          postgres    false    230            ¯           0    0    agiletrack_project_id_seq    SEQUENCE SET     H   SELECT pg_catalog.setval('public.agiletrack_project_id_seq', 21, true);
          public          postgres    false    228            °           0    0    agiletrack_sprint_id_seq    SEQUENCE SET     G   SELECT pg_catalog.setval('public.agiletrack_sprint_id_seq', 11, true);
          public          postgres    false    232            ±           0    0    agiletrack_task_id_seq    SEQUENCE SET     E   SELECT pg_catalog.setval('public.agiletrack_task_id_seq', 31, true);
          public          postgres    false    234            ²           0    0    agiletrack_team_id_seq    SEQUENCE SET     E   SELECT pg_catalog.setval('public.agiletrack_team_id_seq', 95, true);
          public          postgres    false    236            ³           0    0    auth_group_id_seq    SEQUENCE SET     ?   SELECT pg_catalog.setval('public.auth_group_id_seq', 2, true);
          public          postgres    false    215            ´           0    0    auth_group_permissions_id_seq    SEQUENCE SET     L   SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);
          public          postgres    false    217            µ           0    0    auth_permission_id_seq    SEQUENCE SET     E   SELECT pg_catalog.setval('public.auth_permission_id_seq', 56, true);
          public          postgres    false    213            ¶           0    0    django_admin_log_id_seq    SEQUENCE SET     F   SELECT pg_catalog.setval('public.django_admin_log_id_seq', 20, true);
          public          postgres    false    225            ·           0    0    django_content_type_id_seq    SEQUENCE SET     I   SELECT pg_catalog.setval('public.django_content_type_id_seq', 14, true);
          public          postgres    false    211            ¸           0    0    django_migrations_id_seq    SEQUENCE SET     G   SELECT pg_catalog.setval('public.django_migrations_id_seq', 42, true);
          public          postgres    false    209            Ä           2606    17031 T   accounts_employee_groups accounts_employee_groups_employee_id_group_id_8151ad72_uniq 
   CONSTRAINT         ALTER TABLE ONLY public.accounts_employee_groups
    ADD CONSTRAINT accounts_employee_groups_employee_id_group_id_8151ad72_uniq UNIQUE (employee_id, group_id);
 ~   ALTER TABLE ONLY public.accounts_employee_groups DROP CONSTRAINT accounts_employee_groups_employee_id_group_id_8151ad72_uniq;
       public            postgres    false    222    222            Ç           2606    17022 6   accounts_employee_groups accounts_employee_groups_pkey 
   CONSTRAINT     t   ALTER TABLE ONLY public.accounts_employee_groups
    ADD CONSTRAINT accounts_employee_groups_pkey PRIMARY KEY (id);
 `   ALTER TABLE ONLY public.accounts_employee_groups DROP CONSTRAINT accounts_employee_groups_pkey;
       public            postgres    false    222            ¾           2606    17014 (   accounts_employee accounts_employee_pkey 
   CONSTRAINT     f   ALTER TABLE ONLY public.accounts_employee
    ADD CONSTRAINT accounts_employee_pkey PRIMARY KEY (id);
 R   ALTER TABLE ONLY public.accounts_employee DROP CONSTRAINT accounts_employee_pkey;
       public            postgres    false    220            É           2606    17045 b   accounts_employee_user_permissions accounts_employee_user_p_employee_id_permission_i_c232da4c_uniq 
   CONSTRAINT     ³   ALTER TABLE ONLY public.accounts_employee_user_permissions
    ADD CONSTRAINT accounts_employee_user_p_employee_id_permission_i_c232da4c_uniq UNIQUE (employee_id, permission_id);
 Œ   ALTER TABLE ONLY public.accounts_employee_user_permissions DROP CONSTRAINT accounts_employee_user_p_employee_id_permission_i_c232da4c_uniq;
       public            postgres    false    224    224            Í           2606    17028 J   accounts_employee_user_permissions accounts_employee_user_permissions_pkey 
   CONSTRAINT     ˆ   ALTER TABLE ONLY public.accounts_employee_user_permissions
    ADD CONSTRAINT accounts_employee_user_permissions_pkey PRIMARY KEY (id);
 t   ALTER TABLE ONLY public.accounts_employee_user_permissions DROP CONSTRAINT accounts_employee_user_permissions_pkey;
       public            postgres    false    224            Á           2606    17016 0   accounts_employee accounts_employee_username_key 
   CONSTRAINT     o   ALTER TABLE ONLY public.accounts_employee
    ADD CONSTRAINT accounts_employee_username_key UNIQUE (username);
 Z   ALTER TABLE ONLY public.accounts_employee DROP CONSTRAINT accounts_employee_username_key;
       public            postgres    false    220            Ù           2606    17136 "   agiletrack_job agiletrack_job_pkey 
   CONSTRAINT     `   ALTER TABLE ONLY public.agiletrack_job
    ADD CONSTRAINT agiletrack_job_pkey PRIMARY KEY (id);
 L   ALTER TABLE ONLY public.agiletrack_job DROP CONSTRAINT agiletrack_job_pkey;
       public            postgres    false    231            ×           2606    17130 *   agiletrack_project agiletrack_project_pkey 
   CONSTRAINT     h   ALTER TABLE ONLY public.agiletrack_project
    ADD CONSTRAINT agiletrack_project_pkey PRIMARY KEY (id);
 T   ALTER TABLE ONLY public.agiletrack_project DROP CONSTRAINT agiletrack_project_pkey;
       public            postgres    false    229            Û           2606    17148 (   agiletrack_sprint agiletrack_sprint_pkey 
   CONSTRAINT     f   ALTER TABLE ONLY public.agiletrack_sprint
    ADD CONSTRAINT agiletrack_sprint_pkey PRIMARY KEY (id);
 R   ALTER TABLE ONLY public.agiletrack_sprint DROP CONSTRAINT agiletrack_sprint_pkey;
       public            postgres    false    233            ß           2606    17156 $   agiletrack_task agiletrack_task_pkey 
   CONSTRAINT     b   ALTER TABLE ONLY public.agiletrack_task
    ADD CONSTRAINT agiletrack_task_pkey PRIMARY KEY (id);
 N   ALTER TABLE ONLY public.agiletrack_task DROP CONSTRAINT agiletrack_task_pkey;
       public            postgres    false    235            ä           2606    17186 $   agiletrack_team agiletrack_team_pkey 
   CONSTRAINT     b   ALTER TABLE ONLY public.agiletrack_team
    ADD CONSTRAINT agiletrack_team_pkey PRIMARY KEY (id);
 N   ALTER TABLE ONLY public.agiletrack_team DROP CONSTRAINT agiletrack_team_pkey;
       public            postgres    false    237            ³           2606    17005    auth_group auth_group_name_key 
   CONSTRAINT     Y   ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);
 H   ALTER TABLE ONLY public.auth_group DROP CONSTRAINT auth_group_name_key;
       public            postgres    false    216            ¸           2606    16991 R   auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq 
   CONSTRAINT         ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);
 |   ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq;
       public            postgres    false    218    218            »           2606    16980 2   auth_group_permissions auth_group_permissions_pkey 
   CONSTRAINT     p   ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);
 \   ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_pkey;
       public            postgres    false    218            µ           2606    16972    auth_group auth_group_pkey 
   CONSTRAINT     X   ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);
 D   ALTER TABLE ONLY public.auth_group DROP CONSTRAINT auth_group_pkey;
       public            postgres    false    216            ®           2606    16982 F   auth_permission auth_permission_content_type_id_codename_01ab375a_uniq 
   CONSTRAINT     –   ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);
 p   ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq;
       public            postgres    false    214    214            °           2606    16966 $   auth_permission auth_permission_pkey 
   CONSTRAINT     b   ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);
 N   ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_pkey;
       public            postgres    false    214            è           2606    17221 $   authtoken_token authtoken_token_pkey 
   CONSTRAINT     c   ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);
 N   ALTER TABLE ONLY public.authtoken_token DROP CONSTRAINT authtoken_token_pkey;
       public            postgres    false    238            ê           2606    17223 +   authtoken_token authtoken_token_user_id_key 
   CONSTRAINT     i   ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);
 U   ALTER TABLE ONLY public.authtoken_token DROP CONSTRAINT authtoken_token_user_id_key;
       public            postgres    false    238            Ğ           2606    17066 &   django_admin_log django_admin_log_pkey 
   CONSTRAINT     d   ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);
 P   ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_pkey;
       public            postgres    false    226            ©           2606    16960 E   django_content_type django_content_type_app_label_model_76bd3d3b_uniq 
   CONSTRAINT     Œ   ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);
 o   ALTER TABLE ONLY public.django_content_type DROP CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq;
       public            postgres    false    212    212            «           2606    16958 ,   django_content_type django_content_type_pkey 
   CONSTRAINT     j   ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);
 V   ALTER TABLE ONLY public.django_content_type DROP CONSTRAINT django_content_type_pkey;
       public            postgres    false    212            §           2606    16952 (   django_migrations django_migrations_pkey 
   CONSTRAINT     f   ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);
 R   ALTER TABLE ONLY public.django_migrations DROP CONSTRAINT django_migrations_pkey;
       public            postgres    false    210            Ô           2606    17121 "   django_session django_session_pkey 
   CONSTRAINT     i   ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);
 L   ALTER TABLE ONLY public.django_session DROP CONSTRAINT django_session_pkey;
       public            postgres    false    227            Â           1259    17042 -   accounts_employee_groups_employee_id_b9078cfc    INDEX     y   CREATE INDEX accounts_employee_groups_employee_id_b9078cfc ON public.accounts_employee_groups USING btree (employee_id);
 A   DROP INDEX public.accounts_employee_groups_employee_id_b9078cfc;
       public            postgres    false    222            Å           1259    17043 *   accounts_employee_groups_group_id_30ef76d9    INDEX     s   CREATE INDEX accounts_employee_groups_group_id_30ef76d9 ON public.accounts_employee_groups USING btree (group_id);
 >   DROP INDEX public.accounts_employee_groups_group_id_30ef76d9;
       public            postgres    false    222            ¼           1259    17142 !   accounts_employee_job_id_f88f62eb    INDEX     a   CREATE INDEX accounts_employee_job_id_f88f62eb ON public.accounts_employee USING btree (job_id);
 5   DROP INDEX public.accounts_employee_job_id_f88f62eb;
       public            postgres    false    220            Ê           1259    17056 7   accounts_employee_user_permissions_employee_id_b3284276    INDEX        CREATE INDEX accounts_employee_user_permissions_employee_id_b3284276 ON public.accounts_employee_user_permissions USING btree (employee_id);
 K   DROP INDEX public.accounts_employee_user_permissions_employee_id_b3284276;
       public            postgres    false    224            Ë           1259    17057 9   accounts_employee_user_permissions_permission_id_0719c627    INDEX     ‘   CREATE INDEX accounts_employee_user_permissions_permission_id_0719c627 ON public.accounts_employee_user_permissions USING btree (permission_id);
 M   DROP INDEX public.accounts_employee_user_permissions_permission_id_0719c627;
       public            postgres    false    224            ¿           1259    17029 (   accounts_employee_username_ea2313ea_like    INDEX     ~   CREATE INDEX accounts_employee_username_ea2313ea_like ON public.accounts_employee USING btree (username varchar_pattern_ops);
 <   DROP INDEX public.accounts_employee_username_ea2313ea_like;
       public            postgres    false    220            Ü           1259    17162 %   agiletrack_sprint_project_id_9b5307a0    INDEX     i   CREATE INDEX agiletrack_sprint_project_id_9b5307a0 ON public.agiletrack_sprint USING btree (project_id);
 9   DROP INDEX public.agiletrack_sprint_project_id_9b5307a0;
       public            postgres    false    233            İ           1259    17178 $   agiletrack_task_employee_id_948938c1    INDEX     g   CREATE INDEX agiletrack_task_employee_id_948938c1 ON public.agiletrack_task USING btree (employee_id);
 8   DROP INDEX public.agiletrack_task_employee_id_948938c1;
       public            postgres    false    235            à           1259    17179 #   agiletrack_task_project_id_d0363764    INDEX     e   CREATE INDEX agiletrack_task_project_id_d0363764 ON public.agiletrack_task USING btree (project_id);
 7   DROP INDEX public.agiletrack_task_project_id_d0363764;
       public            postgres    false    235            á           1259    17180 "   agiletrack_task_sprint_id_6959b592    INDEX     c   CREATE INDEX agiletrack_task_sprint_id_6959b592 ON public.agiletrack_task USING btree (sprint_id);
 6   DROP INDEX public.agiletrack_task_sprint_id_6959b592;
       public            postgres    false    235            â           1259    17197 $   agiletrack_team_employee_id_cb2a6881    INDEX     g   CREATE INDEX agiletrack_team_employee_id_cb2a6881 ON public.agiletrack_team USING btree (employee_id);
 8   DROP INDEX public.agiletrack_team_employee_id_cb2a6881;
       public            postgres    false    237            å           1259    17198 #   agiletrack_team_project_id_17e74f3f    INDEX     e   CREATE INDEX agiletrack_team_project_id_17e74f3f ON public.agiletrack_team USING btree (project_id);
 7   DROP INDEX public.agiletrack_team_project_id_17e74f3f;
       public            postgres    false    237            ±           1259    17006    auth_group_name_a6ea08ec_like    INDEX     h   CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);
 1   DROP INDEX public.auth_group_name_a6ea08ec_like;
       public            postgres    false    216            ¶           1259    17002 (   auth_group_permissions_group_id_b120cbf9    INDEX     o   CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
 <   DROP INDEX public.auth_group_permissions_group_id_b120cbf9;
       public            postgres    false    218            ¹           1259    17003 -   auth_group_permissions_permission_id_84c5c92e    INDEX     y   CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);
 A   DROP INDEX public.auth_group_permissions_permission_id_84c5c92e;
       public            postgres    false    218            ¬           1259    16988 (   auth_permission_content_type_id_2f476e4b    INDEX     o   CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);
 <   DROP INDEX public.auth_permission_content_type_id_2f476e4b;
       public            postgres    false    214            æ           1259    17229 !   authtoken_token_key_10f0b77e_like    INDEX     p   CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);
 5   DROP INDEX public.authtoken_token_key_10f0b77e_like;
       public            postgres    false    238            Î           1259    17077 )   django_admin_log_content_type_id_c4bce8eb    INDEX     q   CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
 =   DROP INDEX public.django_admin_log_content_type_id_c4bce8eb;
       public            postgres    false    226            Ñ           1259    17078 !   django_admin_log_user_id_c564eba6    INDEX     a   CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);
 5   DROP INDEX public.django_admin_log_user_id_c564eba6;
       public            postgres    false    226            Ò           1259    17123 #   django_session_expire_date_a5c62663    INDEX     e   CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);
 7   DROP INDEX public.django_session_expire_date_a5c62663;
       public            postgres    false    227            Õ           1259    17122 (   django_session_session_key_c0390e0f_like    INDEX     ~   CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);
 <   DROP INDEX public.django_session_session_key_c0390e0f_like;
       public            postgres    false    227            ï           2606    17032 O   accounts_employee_groups accounts_employee_gr_employee_id_b9078cfc_fk_accounts_    FK CONSTRAINT     Ü   ALTER TABLE ONLY public.accounts_employee_groups
    ADD CONSTRAINT accounts_employee_gr_employee_id_b9078cfc_fk_accounts_ FOREIGN KEY (employee_id) REFERENCES public.accounts_employee(id) DEFERRABLE INITIALLY DEFERRED;
 y   ALTER TABLE ONLY public.accounts_employee_groups DROP CONSTRAINT accounts_employee_gr_employee_id_b9078cfc_fk_accounts_;
       public          postgres    false    3262    222    220            ğ           2606    17037 T   accounts_employee_groups accounts_employee_groups_group_id_30ef76d9_fk_auth_group_id    FK CONSTRAINT     ×   ALTER TABLE ONLY public.accounts_employee_groups
    ADD CONSTRAINT accounts_employee_groups_group_id_30ef76d9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;
 ~   ALTER TABLE ONLY public.accounts_employee_groups DROP CONSTRAINT accounts_employee_groups_group_id_30ef76d9_fk_auth_group_id;
       public          postgres    false    3253    216    222            î           2606    17137 H   accounts_employee accounts_employee_job_id_f88f62eb_fk_agiletrack_job_id    FK CONSTRAINT     Í   ALTER TABLE ONLY public.accounts_employee
    ADD CONSTRAINT accounts_employee_job_id_f88f62eb_fk_agiletrack_job_id FOREIGN KEY (job_id) REFERENCES public.agiletrack_job(id) DEFERRABLE INITIALLY DEFERRED;
 r   ALTER TABLE ONLY public.accounts_employee DROP CONSTRAINT accounts_employee_job_id_f88f62eb_fk_agiletrack_job_id;
       public          postgres    false    231    3289    220            ñ           2606    17046 Y   accounts_employee_user_permissions accounts_employee_us_employee_id_b3284276_fk_accounts_    FK CONSTRAINT     æ   ALTER TABLE ONLY public.accounts_employee_user_permissions
    ADD CONSTRAINT accounts_employee_us_employee_id_b3284276_fk_accounts_ FOREIGN KEY (employee_id) REFERENCES public.accounts_employee(id) DEFERRABLE INITIALLY DEFERRED;
 ƒ   ALTER TABLE ONLY public.accounts_employee_user_permissions DROP CONSTRAINT accounts_employee_us_employee_id_b3284276_fk_accounts_;
       public          postgres    false    3262    224    220            ò           2606    17051 [   accounts_employee_user_permissions accounts_employee_us_permission_id_0719c627_fk_auth_perm    FK CONSTRAINT     è   ALTER TABLE ONLY public.accounts_employee_user_permissions
    ADD CONSTRAINT accounts_employee_us_permission_id_0719c627_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;
 …   ALTER TABLE ONLY public.accounts_employee_user_permissions DROP CONSTRAINT accounts_employee_us_permission_id_0719c627_fk_auth_perm;
       public          postgres    false    224    214    3248            õ           2606    17157 P   agiletrack_sprint agiletrack_sprint_project_id_9b5307a0_fk_agiletrack_project_id    FK CONSTRAINT     İ   ALTER TABLE ONLY public.agiletrack_sprint
    ADD CONSTRAINT agiletrack_sprint_project_id_9b5307a0_fk_agiletrack_project_id FOREIGN KEY (project_id) REFERENCES public.agiletrack_project(id) DEFERRABLE INITIALLY DEFERRED;
 z   ALTER TABLE ONLY public.agiletrack_sprint DROP CONSTRAINT agiletrack_sprint_project_id_9b5307a0_fk_agiletrack_project_id;
       public          postgres    false    233    229    3287            ö           2606    17163 L   agiletrack_task agiletrack_task_employee_id_948938c1_fk_accounts_employee_id    FK CONSTRAINT     Ù   ALTER TABLE ONLY public.agiletrack_task
    ADD CONSTRAINT agiletrack_task_employee_id_948938c1_fk_accounts_employee_id FOREIGN KEY (employee_id) REFERENCES public.accounts_employee(id) DEFERRABLE INITIALLY DEFERRED;
 v   ALTER TABLE ONLY public.agiletrack_task DROP CONSTRAINT agiletrack_task_employee_id_948938c1_fk_accounts_employee_id;
       public          postgres    false    220    235    3262            ÷           2606    17168 L   agiletrack_task agiletrack_task_project_id_d0363764_fk_agiletrack_project_id    FK CONSTRAINT     Ù   ALTER TABLE ONLY public.agiletrack_task
    ADD CONSTRAINT agiletrack_task_project_id_d0363764_fk_agiletrack_project_id FOREIGN KEY (project_id) REFERENCES public.agiletrack_project(id) DEFERRABLE INITIALLY DEFERRED;
 v   ALTER TABLE ONLY public.agiletrack_task DROP CONSTRAINT agiletrack_task_project_id_d0363764_fk_agiletrack_project_id;
       public          postgres    false    229    235    3287            ø           2606    17173 J   agiletrack_task agiletrack_task_sprint_id_6959b592_fk_agiletrack_sprint_id    FK CONSTRAINT     Õ   ALTER TABLE ONLY public.agiletrack_task
    ADD CONSTRAINT agiletrack_task_sprint_id_6959b592_fk_agiletrack_sprint_id FOREIGN KEY (sprint_id) REFERENCES public.agiletrack_sprint(id) DEFERRABLE INITIALLY DEFERRED;
 t   ALTER TABLE ONLY public.agiletrack_task DROP CONSTRAINT agiletrack_task_sprint_id_6959b592_fk_agiletrack_sprint_id;
       public          postgres    false    3291    235    233            ù           2606    17187 L   agiletrack_team agiletrack_team_employee_id_cb2a6881_fk_accounts_employee_id    FK CONSTRAINT     Ù   ALTER TABLE ONLY public.agiletrack_team
    ADD CONSTRAINT agiletrack_team_employee_id_cb2a6881_fk_accounts_employee_id FOREIGN KEY (employee_id) REFERENCES public.accounts_employee(id) DEFERRABLE INITIALLY DEFERRED;
 v   ALTER TABLE ONLY public.agiletrack_team DROP CONSTRAINT agiletrack_team_employee_id_cb2a6881_fk_accounts_employee_id;
       public          postgres    false    3262    237    220            ú           2606    17192 L   agiletrack_team agiletrack_team_project_id_17e74f3f_fk_agiletrack_project_id    FK CONSTRAINT     Ù   ALTER TABLE ONLY public.agiletrack_team
    ADD CONSTRAINT agiletrack_team_project_id_17e74f3f_fk_agiletrack_project_id FOREIGN KEY (project_id) REFERENCES public.agiletrack_project(id) DEFERRABLE INITIALLY DEFERRED;
 v   ALTER TABLE ONLY public.agiletrack_team DROP CONSTRAINT agiletrack_team_project_id_17e74f3f_fk_agiletrack_project_id;
       public          postgres    false    229    3287    237            í           2606    16997 O   auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm    FK CONSTRAINT     Ü   ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;
 y   ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm;
       public          postgres    false    3248    218    214            ì           2606    16992 P   auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id    FK CONSTRAINT     Ó   ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;
 z   ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id;
       public          postgres    false    216    3253    218            ë           2606    16983 E   auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co    FK CONSTRAINT     Ø   ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
 o   ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co;
       public          postgres    false    212    214    3243            û           2606    17224 H   authtoken_token authtoken_token_user_id_35299eff_fk_accounts_employee_id    FK CONSTRAINT     Ñ   ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_accounts_employee_id FOREIGN KEY (user_id) REFERENCES public.accounts_employee(id) DEFERRABLE INITIALLY DEFERRED;
 r   ALTER TABLE ONLY public.authtoken_token DROP CONSTRAINT authtoken_token_user_id_35299eff_fk_accounts_employee_id;
       public          postgres    false    238    220    3262            ó           2606    17067 G   django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co    FK CONSTRAINT     Ú   ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
 q   ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co;
       public          postgres    false    212    226    3243            ô           2606    17072 J   django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_employee_id    FK CONSTRAINT     Ó   ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_employee_id FOREIGN KEY (user_id) REFERENCES public.accounts_employee(id) DEFERRABLE INITIALLY DEFERRED;
 t   ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_employee_id;
       public          postgres    false    220    226    3262            ’   `  xœµ–ÛrªH†¯ñ)rá]*ÚİĞX5UÁ3"Æsíª©æŒrŒÀÓ˜¸Ç­™=±P]¨_ÿ¬õ¯™Pİë&ú;¶)Â¤J@ùªbÌOºè5²Rs„d‚F¯›—«§\rµvÜï¯†ÛşP‰ì·ll–ø†Øv]Šø€‘¿İ§£Í_Ì	“0Íà˜8¹K™ŒÆ±ãLl¨Ôaví?)õB×¨iÇ˜Å½ ö	à'(> Ğ@b G ˜=8A-ô-†­°ß‡ûşïä	ˆm ÜÀ¸Æ(@¡„Hª{ÏĞ,8ªÕìŞ—-:îyÉÕ&x€Bƒ+X~ß+7ñ¾XÁß,zØõµKÌ\_\!_ëØÈ7 ß`I‰ìË9£
ùfâD³ãÀèë01µÿ£¯aÅKX58ÅÆáL‹+ÜmÚµî=k9òpf¶¥^¿}òZ=³ZÏÌ¥Â…(’”ÍJÊ›iÓÎİ‰âîúz'¦¸íä³Íj:ÑDá¢oñ4UŸy)NLÓw¬££ÿ?i“€êï¤4 §AÏåêgæ(Q“Å$íUıvÈÕ5\AÁIµ2¶?ïuëJ{RZ”¡—ÓÍgXóRx±Ê0—ø&$y‚ÜCAˆaƒãk È—¬ºaÒ£›Ôv¡Uü`Ş·z¢ï,gÃE”šö~°•\OhVµYG®P‘i6ítGĞ›z=ybî=_wúÈ²–Jvîx"ıÊ{,§O=ã_ê§réÙ’3¼y¸ÅN,¨ŒÄ›ìümt6ÙNEİ0-å•6Ü5‰èÕÜ ˆÆët`]»CzùÑÔuG÷›G°ØJ¤å¼—Ãà#/.RŸ-îWÃûZy€KÏaIazŸ±¹Šx›Zo§]£#öæLŞÚôÕíBªâí[;M£ü¨OíQ6
ÖP˜×_ü•pŒ·‚8ëEc¹5–?§”ßªª–ç{ˆ|‰ØBãš @üîÍ×¤¤ÁmTó¥µÎ<À­Æ1­gN©’VíãkÒFMVÒ×;ÉÆ5&Şò…77ÒvîªQWzÃh5{0ø@MŒ8)³à0?£çòãwâÂÈQqV¬añùLŒ*Ş&*Ë!!¯D$ÛnáŞjµRÜEÕIY¨Û¬û˜¢0™†Ö›
éüà©të6ÜíÒal[ì¥úôõ­àLÊ\]ÜMã¢k ÒÕ ¨AVÄX¸¡2úV3¾0ÿäıŠ•ıĞW€@ø3kánwZİ‹…æKÒ5i=“0ß.&Õ¥¹XÈœŞÌ•ˆÖ³4’÷+:Ü”Ó>¤(­;SÖùz<ªsŸÜ¢(²ë‚»ZşÂë„(*«ñ òw†?oøÌ+ğNÓ·iÓCw¡n×{ÊÍÍv¬ï_ªrsTO:m{Â?Ú^İï{Ñ4Q(ÓÇèq9èTİJş<p"VşìÌô¬Y(ós5X¬Á[Î|ÇŞğ é»òQÛKMuåİ|8#aVS+öÆ;•›sœkÕWkniÓØ×±ÙÍ–ÇiW½…]çàƒ÷ìd•ÿŒÂàjHÄ¼ğ[v”ÈÂmdÉHºÙÁƒ¯Sll¬×uWeí‹ñ|#æ;}¯„ó]º	ê³&hEk<”8¿(rÍ4ûu]}ãôQ{D[L°& {ƒö{ëîgûøÜ9âbâ¤ÎÁ¢˜•‹Á‚+¹$³Äü¿{ñ–¼qŞé @ëå!!¬Ï¶…›‡´9^jòFŞ¶{«Ã}kæõÜÎè5İÌÓñĞà³1ZÒX2w9*øs"*üo¥ñòÀ…kån(ı£V©TşÈ¼Ê      ”   K   xœŒÉÀ0ÃŞÒ0EäNwéşsTB`|(‚P,øq¢Í…	qc™Ûlóâ5}Ã
2‘ ”C™$2Jtì¸±#ß|ÉÍ©      –      xœ‹Ñãââ Å ©         ˜   xœM=Â0Fgûæ ~÷Ha`B¨ªÄÀŠ©"¡§ĞÛ¡Ùì÷ÙÏCÕ]åi<ÓÖµÖ1{02ã£]¸ÇÔ»TÖGÒlëÒ°¢h)¾Rü¸„ƒ*]CÂA’c‚+ĞÜïï¡È“¶K Â5TÜDoe‡5Ã™}ÈAñUÓ¹obœà´3n}º¿÷4EÄ7ûvO|      ›     xœ}SMÓ0=§¿b¸·•“n)—Õ"!Û•¸ìe’LÒÙuìÈvZ-'ş_ÂØI[¡
$K¶&óñæ½—<ë}¦*@=îÙƒœ°'hØù §o­^ Æ€ĞX|`ÓB?¸Şzò`~K™Ô*ä9ø˜TK)9şA5Hrhí¾mS¯=Áó c‚…–ø€.Hš4¡3Sñ¨!G¦"ğ°´C€­uÔÁ§ŞİZ>Äil`‡­TÀ!5+ÖaÁÂ08òY¡ŠÕB­…šo/O‰Y“­òìéK¶Qk¥–JÍòuv÷ğv¯>P—}5ÜÈiÉ¸“ElGN°ê4ßï¹÷pä°O„~·N×¿şòğÖÅ5R?Û„#:ZÂí õ(á¯ÎVä#¯ÂË½æM?¢‘æ=NëÅÅ$aa§Ùl	ëSõ<©4j3ÿ¥ ¿(oÎ\¨Õù¹R‘†&+6ñ~W¨‰Mvk¬,æÎ’˜Ø÷*u-¢„N°¸IœL²(–šDmAâ¨öçùy~%ï\„±gyØSeeõÿšx²­„J3™ .B‡[êbÜ'é“™êQWß»Èbiíè34í Qü:ZÿY9ÆG<ŠÍ¥C'ÌÈÉ¤EBvÁ8xª¯mºY¨›‘„›u¼‹OËÙlöE?ì      Ÿ   Ó   xœİ‚0…¯·§è`Ø@Ñ—ğF/¹Y`ÈWÜÊû»©Ó`bbLºŸ¤§§_[²ÃäŒ%(Ø±7BP¯Ã1®ÿH]°9C«HÁ0{B ßŞØ“œ‰ÕûE4x™FMºe’W,ŠƒòéÆ®]÷©'l1H×‰E<XTèĞÁäpĞMÌÉ\Y¾ÉDşşVÑæ~”'§½g‚ÉQ.¦óºAûÿxO\!˜²ü\ršFem˜:Ö)’‰­^0uÆ…¦?#½&Oû¨2¹‹}ÊíÇ$¯WœóP†—      ¡   {  xœÅVMoã6=S¿b|ÚëDêÓB/A -½ìs¡%Úb"‰I%q}‡”dË‰wO]41‚˜CfŞ¼÷È˜ØFê,7ÏpP­De¡»½ĞÀÈ÷K¼SÕ3ÔÜr¨´àVÔ {°ğk{n<Æú4V+û#£”f†Óy}C¿ºOFjÕÒ‰Z¡,ŠÂ("“ !÷òzş²çzJêKô¹W£¶Í¯®ª‘Ç†SI‰/‰ÆdÙ;!&øÛyÅ×°Ù\
",bñ—(ûBSˆÒ2‰Ê¤söÙu¸DˆŠ’¦eÄÂ,*\ˆfDö8†£ÆL5 ,¾ˆØ!0bD¥úÕĞæïóì®Âÿ):«~hTÒ¢dEH“«~–HŒO­ÁœúÀFü®ĞˆË$+“]ÈRv#ñ®Œã°ÈcZ%f«´¹«k—-¼ğVb§RõğÛˆÍjqo¿{b9Œª$oHÌ,È”²H}vüYø5Lsì/àu²®[ÒòÕ[Ş¶§-î1
Æ_7=ÓÊşÙÀ«tDÅ¯½x¬×¼›}LK‡Yßî6‹4s¡5'³‹LXSÏ@ëÿÎFšªZ-²J.Fxp»#¯kìg4ËCiÀIfÆh¾hÎx&}2PSi984‘æ7VÁÇ×¶ê•ĞË¤ã w.‚øà+ÒZö(1²Ì_"æĞˆŠ,ÎJ…q‘öpøb= ¾Ö”P’;r×+|£+ÕªóìyõÜªãÏ£°Y—6£’^cñ¸‘ÉÊĞË<İÜs-rÎ·ÄÂóÒ~pdô¾2åe«hê“Ò)iB¾5r€ê µªŒŸ–ùÚ(‡´àù&œEàÚ‹ĞÆéÃoö\äÕCn;¼H²ÒÊ¨ƒ…ï¸„Ã4|€ò+“2Ê™Ñ˜®	=…’¤d»p—§ŞçŞãÏ<W2ò·›ğL”Ê©KÎÊã3gÈ_ı…—[8©*ŞÏŒq»Ä€ôÅc_yíc'bÛNÂœ5:·;©aã:4ê'Šöc}6¼ÙU´»Ñ0º>KBJg#<«ãÌ€8HÉh|½#’«K­•"Â6ªŞ‚´ z3¢:±"ng©¶^ËYH„­\:rÑK÷²Ÿü	S¡¾ñ6¸fFge[S“ï €ıÉ9ÆbÎË*eÖP@™3³$
‹È)Š¿æş.:³4ØìıqÙ\ï3¯“N³sy²?~(9HíTñî¶Bx=¹Ñÿdé[ŸYöFhÇÜJ'´¶`Nİ^µOû8	ãüã=€±’²p—Möô£›zxAşTZ»¹ PŸ±3¡µÒfvìËôÉÃÙOg§>ÔøhUç¹47¹Ü€èe;¼´¬fP¸ÓUÔ?rÇiıµ‘Uãx‰f‰6a&¤±„EÂpv‹³BR¢ºĞãÚvÄ’êÃ1h7nOîÍÃ8ñ°å·¯nˆB×'½›(^ê¬ÜfsãMè_›é}uS›'•¯_úAğ/8ùhz      £   V   xœÍÁÀ CÑ³=LE !t—î?GmÄáÁ—Î„ÏÂ2‰4…2Û4Â5‡j0CUL„Yš¯æ£XÃU†³œèëÂ{M¿›¥Mã^ü‡m/o~Éë¯a         #   xœ3äÌMÍMJ-âÑóå2âÌIML2}¸bô¸¸¸ u<ï            xœ‹Ñãââ Å ©      Œ   
  xœ]•Inã0 Ïä+ü‚A¨ÅË9_È1@ Ø„ãÄ–‰ÿ>Rïí›È.€¢$¥ğÚõ›îtÚ\‡ó&÷ez„–õÇ²†e¬ 9~uı9;
·¬<åk.Ä- ÿ^ò?‡­
µb6æév™çËĞ‡
Ôt#n­œÉÎ°;ëçX4ì^	†;ˆåyîc¨Acz±r<'/B’ub„t©T…° q-Ç¡/ËİmÊcÌ¡ÚZwbj¬ÎLVo­ÛOŠßªè¾İ‰õœñn[¦UL{+«y
v°Š‘cÕ‹ª)V‚$1ºÏy
[ĞÉ·ñ:<r•{ˆ …Ü@©(dê'D0åOÃw>–°Ãìq+½0\<c¾wÁ8vÆlêaçŒhåßÃgØƒÍòkW8ÎÈÆ®nÓé06eãN…‘V]ºù'àÈõ1Ö.cšÒ¡¸n	 c0¡ÒÆ¡)sœ.}	ËkeÂ*Ö>LA8L¢|—Bq—H56Ka0K"´Ê’»[Høm^Ÿcã’ä1ß®G&ø*€01òï¦ZâÛğ“ûğû[ÖEl\†° 2®AaX (s­¯à¸V‹%ÑÿË¿Âu(”U!Ğ) õ!Ğ´)˜J¤•â—95æóßºPpßÿÖµ*Œû´&W!ÌàıOŒñ(””t      ¤   Ö  xœ]“I’d!C×Å)rßQ?<ÿ³ôƒ¹ÿšÌŒèv°Ğ!	d‰ÃvùXZæ¢.ÃÓ	ÇÊTÇâO°Oğáıf½ÌQÌş |pKGÛº÷fQ]N0tn]«“nĞÌsƒ/P İ
7Á%o·†¢“‘=Âp÷yt•›¼`¯šÓÄÃ:~ç¿ÅeìÜŸ„æ²3ÜLµœk §c£»äLÑÅ(n¢ó2‡Î/RKÛ=ÖÙ‡r"¬5‹§hô%k t#Øü„ğ ¸Qoõ4è	’¦50‡¤QcÙsåŒsæˆÚ¼pùÜö„Ç‘İ@œwóÛ5¢sN‡N°ˆ!ähWĞde’qšè?Hzs¿¡_€İõ	Òf0æà°Ä6×(ªÚC7'êç]±pÕßè—vx9¢¶}ŸŠª«ômZ2#3»åĞ¢Ià{rÉWk(8nì¹˜…_¡6L¹ÔOJCàd|ˆ ’Á5Å¼ü¹¦ÑÇ/â³µ0;)½HŞ¢ªúêgwkOŸ´²œ\ôd_^Á¼½6Ìß¤Óÿ©íø~‡„½a1¢ËTŸò¥Ù;/:¨œ/tR'ı"éÏ àIŠ³zo2Úß«µö¦Ï,      ˜   Ù  xœ¥”ËnÛ0E×ôWÚ¶&æÁ÷hÑ]ÑUšm©±ÚH.${Ñù÷JQì8TâÊ\ÌÎ{‰‚€x	zI¡iéke> İf[”íÏ¸şÕ_®ïóõ&6·e‘‡ì>ÿQ•wE×¯óOu¼-ó›‡‡a/(år '­3äßƒåg,gh˜ ½­ÀñÀe‹ºjÎ"?oWÏ@•m@”XùKyÉõ«DO^yœ‰4S$³D‡îTÍ³Ìo]Ù6±>ÁÚëzià£–Jlw›:6¥À‹b„Êİ´œ­TìP­ÕmÜTo|JğıB¥²†˜^PÇvu^«ã\³üªj»]v¸}‰'—QÒşğbıÉ*éØ™Q#vëMÙKûúˆi=õÖ %;sÛH)“ƒb	hztŠø÷àdÖ4<¨k‰ÎÏ5;¦ùA=Ìì¹¹ÌC‚Ìl6¸Ê…RŒÎ²âOìºª)»r«³ä¯ûße»ï’u»¸Ûw'MÌi“~ëÚôö“¨œgóbñ3ùvÊG–J1à43{¸i"©X{RççßOù’-â¨Ñø6›àÈFÌz‡Ùw–_ÚÓ’ßıcËïr±Xü¶›Ï±      Š      xœ]KÂ0D×Ã BËï.lB°JÚ&W"·§j…(l,ûiFã1dÁG¥ã¨¹â@vÒ'%ÎÁ—â%¢YI—eJhÉIÔYª5qÙ8RáÅQ>Nd“)j!i”ÊŒ3ÙÎ¬ÙºR–â²…½Üqİµe€ÙoQIÙG…1?:¶fm 2p¤eÂ4ÿhÎ}U˜öûßZï¶ğ÷^Ò      ˆ   u  xœ–İ›<†³W±çŸÙã®å“,7qSºü¤ÆTÍİw0à–m¢=‰ÈûØ3óÎØôpìÚèÛ¯ß!ÔVm+W€ {#âêW€’²’ğ‚)¢ıø |Óıöv~aÇ7¶ußGªA(vpCüñxq®¸1*xV€uuôÁ^|hª¾¯º6­h÷ÇÖ¾=ã¿vQ¸4K(‘QlF=~øÆUõCŠQZò‘"3…ßSÆ´îû]„ LË‘ 2AÜj×G[wç
ãêı¼šÁÑ"±¿†*äj¤2Ù1cûÆ´P#Ãd†š7òÛÕÕÉÅ.ôÖNÖ‡ĞÛø¾wgÿITw4Â(É4½›˜ıf‰f’ù §PJh˜P° (™QçĞ—ç0†Ï@³o)µÃ3äí%t®wfÜO$F³”lšLá>ªïUx2,	r.>E+İĞÆ'YQ¹d½{jªö	`‹Fİ40Ú®KÿcDİè”}ˆBÈ»¾AØ2ZÌãØÉßkw¶Ç]uüÄgÊ`MSûP´í¹ª}îøş8ôú<J€l„€½©»«Ÿf—®·ıĞ4.\÷YZ.3‘nXlIIF´~yšĞË+l®öd›.ìKCÔÔR ‡ŞÏæz§áj.°ÍŞøG¡y¥¼¬dPPô‡J£øF¸Ì'ôúOŒö4—ÊõqÿT%Ó%Õã€¶O@±Ê¯±òtJ»Ü Õ×€Fã´I@µê/9åËõhìÏîÛ¾HPI§Ä›U?ßùòS­6slãjtı%Tã¡Œ[‰õXq"

Š³ä0¶±1·%ğoÃéìcşyìpJEïšü$»9¯ä•Ğ’@	x`Rá¥5`»7“>pìøÔ·Œ­ Ë±›1Uƒ§Sf0:Z›CIT!ˆ‘ÊÂ6ÖÎ3xjL¬mêwÏúèBLOwÑ¯(rÊáÆä4‚ûÜÍùFÔ+P,a	¤BòéVÁä*F±ñæƒÁ.R¯±éZ»w¿;à×:)çé,az­ƒi¨¡’ HKW»Å€§éÎÌšÀlúšÈ}%ÇÅ§ÛY…-ÿUZd¤'^a€°Éœ®j:áW"]R‚*€k	)ß|mJmO+è÷µ¸oZ%$¤Œı_¼¼¼üœĞ,      ™   d  xœÕÒËrª0  ĞuıŠîïèäAÂN­ÚŠ¨QétÆ	È³	Ò" |}{7÷î/œ9IT§Ùğ(?
xÅt\i÷4‰×cñRïº~êŠŸ¿z«ñLÙš?J·ËÙÌ\À«`	£jå;ãË¶]êE(áƒ²Ãb~ÕGy	›Ï5ó_Œé^&ñ;	›º_ŸÛÅö®Å°÷(–4é¢c|ÇgqHÃ~^”÷H¼Ôµ¥Ÿ«Õ6-d£}gq*øl•¼©„¾¸-RÃ8ê²¿ó"¢ü"¾Z• ×méä¢–"€›ŞøšÆílR49×] vê­1õÌ@xèàghZXN8? ŒR»,a<¾Iê¦•æw^åmfä¤%·<ş/ØÜ­ªU«7j÷ò]Ú,!qÓ=©N-3*ttRu‰7®«F=#l!b2aô÷ù×èc2~ {«¼     