# Generated by Django 4.2.1 on 2023-05-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agiletrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.TextField(default='yassine'),
        ),
        migrations.AddField(
            model_name='task',
            name='summary',
            field=models.TextField(default='task'),
        ),
    ]
