# Generated by Django 4.2.1 on 2023-05-18 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agiletrack', '0002_employee_name_task_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employees',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
