# Generated by Django 4.2.1 on 2023-05-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agiletrack', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(),
        ),
    ]
