# Generated by Django 4.2.1 on 2023-05-19 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agiletrack', '0009_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('goal', models.CharField(max_length=250)),
                ('start_date', models.DateField(null=True)),
                ('estimated_end_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('estimated_duration', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('status', models.CharField(default='todo', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agiletrack.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('status', models.CharField(default='todo', max_length=20)),
                ('priority', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agiletrack.project')),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agiletrack.sprint')),
            ],
        ),
    ]
